// <auto-generated />
using System;
using LibraryNetwork.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryNetwork.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260218174307_SeedDataAdded")]
    partial class SeedDataAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryNetwork.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ISBN")
                        .IsUnique()
                        .HasFilter("[ISBN] IS NOT NULL");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert C. Martin",
                            Category = "Software",
                            Description = "Writing readable, maintainable code.",
                            ISBN = "9780132350884",
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Andrew Hunt, David Thomas",
                            Category = "Software",
                            Description = "Classic tips for better development.",
                            ISBN = "9780201616224",
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            Category = "Fiction",
                            Description = "Dystopian novel.",
                            ISBN = "9780451524935",
                            Title = "1984"
                        },
                        new
                        {
                            Id = 4,
                            Author = "J.R.R. Tolkien",
                            Category = "Fantasy",
                            Description = "Adventure story.",
                            ISBN = "9780547928227",
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Yuval Noah Harari",
                            Category = "History",
                            Description = "A brief history of humankind.",
                            ISBN = "9780062316097",
                            Title = "Sapiens"
                        });
                });

            modelBuilder.Entity("LibraryNetwork.Models.BookCopy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("InventoryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("LibraryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("InventoryCode")
                        .IsUnique()
                        .HasFilter("[InventoryCode] IS NOT NULL");

                    b.HasIndex("LibraryId");

                    b.ToTable("BookCopies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            InventoryCode = "BM-CC-001",
                            IsAvailable = true,
                            LibraryId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 3,
                            InventoryCode = "BM-1984-001",
                            IsAvailable = false,
                            LibraryId = 1
                        },
                        new
                        {
                            Id = 3,
                            BookId = 2,
                            InventoryCode = "NB-PP-001",
                            IsAvailable = true,
                            LibraryId = 2
                        },
                        new
                        {
                            Id = 4,
                            BookId = 4,
                            InventoryCode = "NB-HOB-001",
                            IsAvailable = true,
                            LibraryId = 2
                        },
                        new
                        {
                            Id = 5,
                            BookId = 5,
                            InventoryCode = "BT-SAP-001",
                            IsAvailable = true,
                            LibraryId = 3
                        },
                        new
                        {
                            Id = 6,
                            BookId = 3,
                            InventoryCode = "BT-1984-002",
                            IsAvailable = true,
                            LibraryId = 3
                        },
                        new
                        {
                            Id = 7,
                            BookId = 1,
                            InventoryCode = "GD-CC-002",
                            IsAvailable = true,
                            LibraryId = 4
                        },
                        new
                        {
                            Id = 8,
                            BookId = 4,
                            InventoryCode = "SP-HOB-002",
                            IsAvailable = false,
                            LibraryId = 5
                        });
                });

            modelBuilder.Entity("LibraryNetwork.Models.Librarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LibraryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("Librarians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Kristina",
                            LastName = "Kitrozoska",
                            LibraryId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Angela",
                            LastName = "Nastovska",
                            LibraryId = 2
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Monika",
                            LastName = "Stoilkovska",
                            LibraryId = 3
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Ivan",
                            LastName = "Perchuklieski",
                            LibraryId = 4
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Andrej",
                            LastName = "Chochov",
                            LibraryId = 5
                        });
                });

            modelBuilder.Entity("LibraryNetwork.Models.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Libraries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ul. Makedonija 12",
                            City = "Skopje",
                            Name = "Brakja Miladinovci"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bul. Goce Delcev 5",
                            City = "Skopje",
                            Name = "Nacionalna Biblioteka"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ul. Ilinden 45",
                            City = "Prilep",
                            Name = "Borka Taleski"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Ul. Partizanska 8",
                            City = "Stip",
                            Name = "Goce Delcev"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Ul. 7-mi Septemvri 22",
                            City = "Kavadarci",
                            Name = "Strasho Pindzur"
                        });
                });

            modelBuilder.Entity("LibraryNetwork.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookCopyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<float?>("FineAmount")
                        .HasColumnType("real");

                    b.Property<DateTime?>("FinePaidDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFinePaid")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookCopyId");

                    b.HasIndex("MemberId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookCopyId = 2,
                            BorrowDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinePaid = false,
                            MemberId = 1,
                            Semester = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            BookCopyId = 8,
                            BorrowDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinePaid = false,
                            MemberId = 2,
                            Semester = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            BookCopyId = 3,
                            BorrowDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0f,
                            FinePaidDate = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinePaid = true,
                            MemberId = 3,
                            ReturnDate = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Semester = 0,
                            Status = 2
                        });
                });

            modelBuilder.Entity("LibraryNetwork.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MembershipNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MembershipNumber")
                        .IsUnique()
                        .HasFilter("[MembershipNumber] IS NOT NULL");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Risto",
                            LastName = "Kizov",
                            MembershipNumber = "MBR-0001"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Sandra",
                            LastName = "Shandarovska",
                            MembershipNumber = "MBR-0002"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Tea",
                            LastName = "Domazetovikj",
                            MembershipNumber = "MBR-0003"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Borjan",
                            LastName = "Petrevski",
                            MembershipNumber = "MBR-0004"
                        });
                });

            modelBuilder.Entity("LibraryNetwork.Models.BookCopy", b =>
                {
                    b.HasOne("LibraryNetwork.Models.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryNetwork.Models.Library", "Library")
                        .WithMany("BookCopies")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("LibraryNetwork.Models.Librarian", b =>
                {
                    b.HasOne("LibraryNetwork.Models.Library", "Library")
                        .WithMany("Librarians")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("LibraryNetwork.Models.Loan", b =>
                {
                    b.HasOne("LibraryNetwork.Models.BookCopy", "BookCopy")
                        .WithMany("Loans")
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryNetwork.Models.Member", "Member")
                        .WithMany("Loans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryNetwork.Models.Book", b =>
                {
                    b.Navigation("BookCopies");
                });

            modelBuilder.Entity("LibraryNetwork.Models.BookCopy", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("LibraryNetwork.Models.Library", b =>
                {
                    b.Navigation("BookCopies");

                    b.Navigation("Librarians");
                });

            modelBuilder.Entity("LibraryNetwork.Models.Member", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
